config/routes.rb
Rails.application.routes.draw do  
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
  resources :videos
  resources :baiviets
    
  resources :banthangs

  resources :phamlois

  resources :thephats

  resources :chitiettrandaus

  resources :trandaus

  resources :lichthidaus

  resources :chitietbxhs

  resources :bangxephangs

  resources :vongdaus

  resources :sanvandongs

  resources :cauthus

  resources :loaimedia

  resources :lenxuonghangs

  resources :doibongs

  resources :vitris

  resources :huanluyenviens

  resources :baiviets

  get 'home/index'
  get '/admin/index', to: 'admin#index', as: 'admin_index'
  
  get 'home/index',to: 'home#index', as: 'index'
  get '/home/news', to: 'home#news', as: 'news'
  get '/home/watch', to: 'home#watch', as: 'watch'
  get '/home/players', to: 'home#players', as: 'players'
  get '/home/stats', to: 'home#stats', as: 'stats'
  get '/home/about', to: 'home#about', as: 'about'
  get '/home/fanzone', to: 'home#fanzone', as: 'fanzone'
  get '/home/chitietdoibong/:id', to: 'home#chitietdoibong', as: 'chitietdoibong'
  get '/home/chitietdoibong/:id', to: 'home#tinmoi_doibong', as: 'tinmoi_doibong'
  get '/home/dulieu_doibong/:id', to: 'home#dulieu_doibong', as: 'dulieu_doibong'
  get '/home/cauthu_doibong/:id', to: 'home#cauthu_doibong', as: 'cauthu_doibong'
  get '/home/ltd_doibong/:id', to: 'home#ltd_doibong', as: 'ltd_doibong'
  get '/home/sanvandong_doibong/:id', to: 'home#sanvandong_doibong', as: 'sanvandong_doibong'
  get '/home/chitiet_baiviet/:id', to: 'home#chitiet_baiviet', as: 'chitiet_baiviet'
  get '/home/chitiet_video/:id', to: 'home#chitiet_video', as: 'chitiet_video'
  
  root to: "home#index"
  post '/change_locale/:locale', to: 'setting#change_locale', as: :change_locale
  post '/change_stat/:stt', to: 'home#change_stat', as: :change_stat
  post '/find_cauthu_ten', to: 'home#find_cauthu_ten', as: :find_cauthu_ten
  
  
  post '/admin_xuly', to: 'admin#xuly', as: :admin_xuly
  

end

app/models/baiviet.rb
class Baiviet < ActiveRecord::Base
end

app/models/bangxephang.rb
class Bangxephang < ActiveRecord::Base
  belongs_to :vongdau
end

app/models/banthang.rb
class Banthang < ActiveRecord::Base
  belongs_to :cauthu
  belongs_to :chitiettrandau
end

app/models/cauthu.rb
class Cauthu < ActiveRecord::Base
  belongs_to :vitri
  belongs_to :doibong
end

app/models/chitietbxh.rb
class Chitietbxh < ActiveRecord::Base
  belongs_to :bangxephang
  belongs_to :doibong
  belongs_to :lenxuonghang
end

app/models/doibong.rb
class Doibong < ActiveRecord::Base
  belongs_to :huanluyenvien
end

app/models/huanluyenvien.rb
class Huanluyenvien < ActiveRecord::Base
end

app/models/lenxuonghang.rb
class Lenxuonghang < ActiveRecord::Base
end

app/models/lichthidau.rb
class Lichthidau < ActiveRecord::Base
  belongs_to :vongdau
end

app/models/loaimedium.rb
class Loaimedium < ActiveRecord::Base
end

app/models/phamloi.rb
class Phamloi < ActiveRecord::Base
  belongs_to :thephat
  belongs_to :cauthu
  belongs_to :chitiettrandau
end

app/models/sanvandong.rb
class Sanvandong < ActiveRecord::Base
  belongs_to :doibong
end

app/models/thephat.rb
class Thephat < ActiveRecord::Base
end

app/models/trandau.rb
class Trandau < ActiveRecord::Base
  has_one :doinha, :class_name => "doibong"
  has_one :doikhach, :class_name => "doibong"
  belongs_to :vongdau
  belongs_to :sanvandong
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/videos.rb
class Videos < ActiveRecord::Base
end

app/models/vitri.rb
class Vitri < ActiveRecord::Base
end

app/models/vongdau.rb
class Vongdau < ActiveRecord::Base
end

app/controllers/chitietbxhs_controller.rb
class ChitietbxhsController < ApplicationController
  before_action :set_chitietbxh, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @chitietbxhs = Chitietbxh.all
    respond_with(@chitietbxhs)
  end

  def show
    respond_with(@chitietbxh)
  end

  def new
    @chitietbxh = Chitietbxh.new
    respond_with(@chitietbxh)
  end

  def edit
  end

  def create
    @chitietbxh = Chitietbxh.new(chitietbxh_params)
    @chitietbxh.save
    respond_with(@chitietbxh)
  end

  def update
    @chitietbxh.update(chitietbxh_params)
    respond_with(@chitietbxh)
  end

  def destroy
    @chitietbxh.destroy
    respond_with(@chitietbxh)
  end

  private
    def set_chitietbxh
      @chitietbxh = Chitietbxh.find(params[:id])
    end

    def chitietbxh_params
      params.require(:chitietbxh).permit(:thuhang, :sotranthidau, :diem, :hieuso, :tongsobanthang, :sotranthang, :sotranghoa, :sotrangthua, :bangxephang_id, :doibong_id, :lenxuonghang_id)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/chitietbxhs_helper.rb
module ChitietbxhsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chitietbxhs/_form.html.erb
<div class="row">
	<div class="col-md-4 col-md-offset-4">
		<%= form_for(@chitietbxh) do |f| %>
		  <% if @chitietbxh.errors.any? %>
		    <div id="error_explanation">
		      <h2><%= pluralize(@chitietbxh.errors.count, "error") %> prohibited this chitietbxh from being saved:</h2>
		
		      <ul>
		      <% @chitietbxh.errors.full_messages.each do |message| %>
		        <li><%= message %></li>
		      <% end %>
		      </ul>
		    </div>
		  <% end %>
		
		  <div class="field">
		    <%= f.label :thuhang,"Rating number" %><br>
		    <%= f.text_field :thuhang , :class=>"form-control"%>
		  </div>
		  <div class="field">
		    <%= f.label :sotranthidau, "Number of match played" %><br>
		    <%= f.text_field :sotranthidau , :class=>"form-control"%>
		  </div>
		  <div class="field">
		    <%= f.label :diem, "Point" %><br>
		    <%= f.text_field :diem, :class=>"form-control" %>
		  </div>
		  <div class="field">
		    <%= f.label :tongsobanthua, "Sum of lost goal" %><br>
		    <%= f.text_field :tongsobanthua, :class=>"form-control" %>
		  </div>
		  <div class="field">
		    <%= f.label :tongsobanthang, "Sum of goal"%><br>
		    <%= f.text_field :tongsobanthang , :class=>"form-control"%>
		  </div>
		  <div class="field">
		    <%= f.label :sotranthang, "Number of Win" %><br>
		    <%= f.text_field :sotranthang , :class=>"form-control"%>
		  </div>
		  <div class="field">
		    <%= f.label :sotranghoa , "Number of Draw"%><br>
		    <%= f.text_field :sotranghoa, :class=>"form-control" %>
		  </div>
		  <div class="field">
		    <%= f.label :sotrangthua , "Number of Lost"%><br>
		    <%= f.text_field :sotrangthua, :class=>"form-control" %>
		  </div>


		  <div class="field">
		   <%= f.label :bangxephang_id, "Stat" %><br>    
			    <%= f.select(:bangxephang_id,[],{},{:class =>"form-control"} ) do %>
			  		<% Bangxephang.all.each do |c| -%>
			    	<%= content_tag(:option, Vongdau.where(:id=>c.id).first.stt, value: c.id) %>
			  	<% end %>
				<% end %>
		  </div>
		  <div class="field">
		   <%= f.label :doibong_id, "Club"%><br>    
			    <%= f.select(:doibong_id,[],{},{:class =>"form-control"} ) do %>
			  		<% Doibong.all.each do |c| -%>
			    	<%= content_tag(:option, c.ten, value: c.id) %>
			  	<% end %>
				<% end %>
		  </div>
		  <div class="field">
		   <%= f.label :lenxuonghang_id, "Rating" %><br>    
			    <%= f.select(:lenxuonghang_id,[],{},{:class =>"form-control"} ) do %>
			  		<% Lenxuonghang.all.each do |c| -%>
			    	<%= content_tag(:option, c.ten, value: c.id) %>
			  	<% end %>
				<% end %>
		  </div>
		  <div class="actions">
		    <%= f.submit "Submit", :class=>"btn btn-success"%>
		  </div>
		<% end %>
	</div>
</div>

app/views/chitietbxhs/_index.html.erb
<h1 class="text-center">Listing Stat Details</h1>

<table class="table">
  <thead>
    <tr>
      <th>Rate Number</th>
      <th>Number of match played</th>
      <th>Point</th>
      <th>Sum of lost goal:</th>
      <th>Sum of goal:</th>
      <th>Number of Win:</th>
      <th>Number of Draw:</th>
      <th>Number of lost:</th>
      <th>Stat:</th>
      <th>Club:</th>
      <th>Rating:</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @chitietbxhs.each do |chitietbxh| %>
      <tr>
        <td><%= chitietbxh.thuhang %></td>
        <td><%= chitietbxh.sotranthidau %></td>
        <td><%= chitietbxh.diem %></td>
        <td><%= chitietbxh.tongsobanthua %></td>
        <td><%= chitietbxh.tongsobanthang %></td>
        <td><%= chitietbxh.sotranthang %></td>
        <td><%= chitietbxh.sotranghoa %></td>
        <td><%= chitietbxh.sotrangthua %></td>
        <td><%= Vongdau.find(Bangxephang.find(chitietbxh.bangxephang).vongdau).stt %></td>
        <td><%= Doibong.find(chitietbxh.doibong ).ten%></td>
        <td><%= Lenxuonghang.find(chitietbxh.lenxuonghang).ten %></td>
        <td><%= link_to 'Show', chitietbxh %></td>
        <td><%= link_to 'Edit', edit_chitietbxh_path(chitietbxh) %></td>
        <td><%= link_to 'Destroy', chitietbxh, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stat Details', new_chitietbxh_path %>

app/views/chitietbxhs/edit.html.erb
<h1 class = "text-center">Editing Stat Detail</h1>

<%= render 'form' %>

<%= link_to 'Show', @chitietbxh %> |
<%= link_to 'Back', admin_index_path %>

app/views/chitietbxhs/new.html.erb
<h1 class="text-center">New Stat Detail</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_index_path %>

app/views/chitietbxhs/show.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">

		<p id="notice"><%= notice %></p>
		
		<p>
		  <strong>Rate Number</strong>
		  <%= @chitietbxh.thuhang %>
		</p>
		
		<p>
		  <strong>Number of match played</strong>
		  <%= @chitietbxh.sotranthidau %>
		</p>
		
		<p>
		  <strong>Point</strong>
		  <%= @chitietbxh.diem %>
		</p>
		
		<p>
		  <strong>Sum of lost goal:</strong>
		  <%= @chitietbxh.tongsobanthua %>
		</p>
		
		<p>
		  <strong>Sum of goal:</strong>
		  <%= @chitietbxh.tongsobanthang %>
		</p>
		
		<p>
		  <strong>Number of Win:</strong>
		  <%= @chitietbxh.sotranthang %>
		</p>
		
		<p>
		  <strong>Number of Draw:</strong>
		  <%= @chitietbxh.sotranghoa %>
		</p>
		
		<p>
		  <strong>Number of lost:</strong>
		  <%= @chitietbxh.sotrangthua %>
		</p>
		
		<p>
		  <strong>Stat:</strong>
		  <%= Vongdau.find(Bangxephang.find(@chitietbxh.bangxephang).vongdau_id).stt %>
		</p>
		
		<p>
		  <strong>Club:</strong>
		  <%= Doibong.find(@chitietbxh.doibong).ten %>
		</p>
		
		<p>
		  <strong>Rating:</strong>
		  <%= Lenxuonghang.find(@chitietbxh.lenxuonghang).ten %>
		</p>
		
		<%= link_to 'Edit', edit_chitietbxh_path(@chitietbxh) %> |
		<%= link_to 'Back', admin_index_path %>
	</div>
</div>