config/routes.rb
Rails.application.routes.draw do  
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
  resources :videos
  resources :baiviets
    
  resources :banthangs

  resources :phamlois

  resources :thephats

  resources :chitiettrandaus

  resources :trandaus

  resources :lichthidaus

  resources :chitietbxhs

  resources :bangxephangs

  resources :vongdaus

  resources :sanvandongs

  resources :cauthus

  resources :loaimedia

  resources :lenxuonghangs

  resources :doibongs

  resources :vitris

  resources :huanluyenviens

  resources :baiviets

  get 'home/index'
  get '/admin/index', to: 'admin#index', as: 'admin_index'
  
  get 'home/index',to: 'home#index', as: 'index'
  get '/home/news', to: 'home#news', as: 'news'
  get '/home/watch', to: 'home#watch', as: 'watch'
  get '/home/players', to: 'home#players', as: 'players'
  get '/home/stats', to: 'home#stats', as: 'stats'
  get '/home/about', to: 'home#about', as: 'about'
  get '/home/fanzone', to: 'home#fanzone', as: 'fanzone'
  get '/home/chitietdoibong/:id', to: 'home#chitietdoibong', as: 'chitietdoibong'
  get '/home/chitietdoibong/:id', to: 'home#tinmoi_doibong', as: 'tinmoi_doibong'
  get '/home/dulieu_doibong/:id', to: 'home#dulieu_doibong', as: 'dulieu_doibong'
  get '/home/cauthu_doibong/:id', to: 'home#cauthu_doibong', as: 'cauthu_doibong'
  get '/home/ltd_doibong/:id', to: 'home#ltd_doibong', as: 'ltd_doibong'
  get '/home/sanvandong_doibong/:id', to: 'home#sanvandong_doibong', as: 'sanvandong_doibong'
  get '/home/chitiet_baiviet/:id', to: 'home#chitiet_baiviet', as: 'chitiet_baiviet'
  get '/home/chitiet_video/:id', to: 'home#chitiet_video', as: 'chitiet_video'
  
  root to: "home#index"
  post '/change_locale/:locale', to: 'setting#change_locale', as: :change_locale
  post '/change_stat/:stt', to: 'home#change_stat', as: :change_stat
  post '/find_cauthu_ten', to: 'home#find_cauthu_ten', as: :find_cauthu_ten
  
  
  post '/admin_xuly', to: 'admin#xuly', as: :admin_xuly
  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # before_action :authenticate_user!
  skip_before_action :verify_authenticity_token
  def index 
    @chitietbxhs = Chitietbxh.where(:bangxephang_id => Vongdau.last.stt)
    connection = ActiveRecord::Base.connection
     @baiviets = connection.execute("select * from baiviets  order by id desc  limit 0,6")
     @videos = connection.execute("select * from videos order by id desc  limit 0,6")
     @baivietmois = connection.execute("select * from baiviets where loaibaiviet=1 order by id desc limit 0,8")
     @championleagues = connection.execute("select * from baiviets where loaibaiviet=3 order by id desc limit 0,8")
     end
  
  def news
    @chitietbxhs = Chitietbxh.where(:bangxephang_id => Vongdau.last.stt)
    connection = ActiveRecord::Base.connection
     @baiviets = connection.execute("select * from baiviets order by id desc ")
     @baivietmois = connection.execute("select * from baiviets where loaibaiviet=1 order by id desc limit 0,8")
     @championleagues = connection.execute("select * from baiviets where loaibaiviet=3 order by id desc limit 0,8")
  end
  
  def watch
    @chitietbxhs = Chitietbxh.where(:bangxephang_id => Vongdau.last.stt)
    connection = ActiveRecord::Base.connection
     @videos = connection.execute("select * from videos order by id desc ")
     @baivietmois = connection.execute("select * from baiviets where loaibaiviet=1 order by id desc limit 0,8")
     @championleagues = connection.execute("select * from baiviets where loaibaiviet=3 order by id desc limit 0,8")
  end
  
  def about
    @chitietbxhs = Chitietbxh.where(:bangxephang_id => Vongdau.last.stt)
    connection = ActiveRecord::Base.connection
    @baivietmois = connection.execute("select * from baiviets where loaibaiviet=1 order by id desc limit 0,8")
    @championleagues = connection.execute("select * from baiviets where loaibaiviet=3 order by id desc limit 0,8")
    
  end
  
  def fanzone
    @chitietbxhs = Chitietbxh.where(:bangxephang_id => Vongdau.last.stt)
    connection = ActiveRecord::Base.connection
    @baivietmois = connection.execute("select * from baiviets where loaibaiviet=1 order by id desc limit 0,8")
    @championleagues = connection.execute("select * from baiviets where loaibaiviet=3 order by id desc limit 0,8")
  end
  
  def players
    @doibong = Doibong.find(1)
    @huanluyenvien = Huanluyenvien.find(@doibong.huanluyenvien_id)
    @cauthus = Cauthu.where(:doibong_id =>@doibong.id)
    if session[:keyword_string]!= nil
      @cauthu_timkiem = @cauthus.where("ten LIKE '%"+session[:keyword_string].to_s+"%'")
      session[:keyword_string]= nil
    end
  end
  
  def stats
    @vongdaus = Vongdau.all 
    if session[:stt]!= nil
      stt = session[:stt]
    else
      stt = 1
    end   
    @chitietbxhs = Chitietbxh.where(:bangxephang_id => stt)
    @trandaus = Trandau.where(:vongdau_id => stt)
    connection = ActiveRecord::Base.connection
    @baivietmois = connection.execute("select * from baiviets where loaibaiviet=1 order by id desc limit 0,8")
    @championleagues = connection.execute("select * from baiviets where loaibaiviet=3 order by id desc limit 0,8")
  end
  
  def change_stat 
    vongdau_id = params[:stt].to_i 
    session[:stt] = vongdau_id  
    render :js => "document.location.reload()"   
  end
  
  
  def chitietdoibong
      doibong = Doibong.find(params[:id].to_i)
      @huanluyenvien = Huanluyenvien.find(doibong.huanluyenvien_id)
      connection = ActiveRecord::Base.connection
      @baiviets = connection.execute("select * from baiviets where doibong_id=#{doibong.id} ")
      @videos = connection.execute("select * from videos where nguon=#{doibong.id}")
      @doibong = Doibong.find(doibong.id)
  end
  
  def tinmoi_doibong
    doibong = Doibong.find(params[:id].to_i)
    @huanluyenvien = Huanluyenvien.find(doibong.huanluyenvien_id)
    @doibong = Doibong.find(doibong.id)
  end
  
  def dulieu_doibong
    doibong = Doibong.find(params[:id].to_i)
    @huanluyenvien = Huanluyenvien.find(doibong.huanluyenvien_id)
    @doibong = Doibong.find(doibong.id)
  end
  
  def cauthu_doibong
    @doibong = Doibong.find(params[:id].to_i)
    @huanluyenvien = Huanluyenvien.find(@doibong.huanluyenvien_id)
    @cauthus = Cauthu.where(:doibong_id =>@doibong.id)
    if session[:keyword_string]!= nil
      @cauthu_timkiem = @cauthus.where("ten LIKE '%"+session[:keyword_string].to_s+"%'")
      session[:keyword_string]= nil
    end
  end
  
  def ltd_doibong
  
    doibong = Doibong.find(params[:id].to_i)
      @huanluyenvien = Huanluyenvien.find(doibong.huanluyenvien_id)
      connection = ActiveRecord::Base.connection
      @trandaus = connection.execute("select * from trandaus where doinha_id =#{doibong.id} or doikhach_id =#{doibong.id}")
      @doibong = Doibong.find(doibong.id)
  end
  
  def sanvandong_doibong
    doibong = Doibong.find(params[:id].to_i)
    @huanluyenvien = Huanluyenvien.find(doibong.huanluyenvien_id)
    @sanvandong = Sanvandong.find(doibong.id)
    @doibong = Doibong.find(doibong.id)
  end
  
  def chitiet_baiviet
    @chitietbxhs = Chitietbxh.where(:bangxephang_id => Vongdau.last.stt)
    @baiviet = Baiviet.find(params[:id].to_i)
    connection = ActiveRecord::Base.connection
    @baiviets = connection.execute("select * from baiviets order by id desc")
    @baivietmois = connection.execute("select * from baiviets where loaibaiviet=1 order by id desc")
    @championleagues = connection.execute("select * from baiviets where loaibaiviet=3 order by id desc limit 0,8")

  end
  
  def find_cauthu_ten
    session[:keyword_string] = params[:keyword].to_s 
    render :js => "document.location.reload()"
  end  
  def chitiet_video
    @chitietbxhs = Chitietbxh.where(:bangxephang_id => Vongdau.last.stt)
    @video = Videos.find(params[:id].to_i)
    connection = ActiveRecord::Base.connection
    @videos = connection.execute("select * from videos where nguon=2")
    @championleagues = connection.execute("select * from baiviets where loaibaiviet=3 order by id desc limit 0,8")
    @baivietmois = connection.execute("select * from baiviets where loaibaiviet=1 order by id desc")
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_cauthu_mini_item.html.erb
<div class="col-md-10">
  <%if @cauthu_timkiem != nil%>	 
	  <%@cauthu_timkiem.each do |ct|%>	  	
		  <img alt='<%= ct.ten%>' height='30' src='<%= '/assets/cauthus/'+ ct.hinhanh %>' width='30'>		  
  		<center >
			  <a style="margin-top:10px;color: black " data-toggle="modal" data-target="#myModal<%= ct.id%>"+"right" ><%= ct.ten%></a>
			</center>
			  <!-- Modal -->
		  
			<div class="modal fade" id="myModal<%= ct.id%>"+"right" role="dialog">
				<div class="modal-dialog">
				
				  <!-- Modal content-->
				  <div class="modal-content">
				    <div class="modal-header">
				      <button type="button" class="close" data-dismiss="modal">&times;</button>
				      <h4 class="modal-title"><center><%= ct.ten%></center></h4>
				    </div>
				    <div class="modal-body">
				    	<div class="row text-center">
							<img alt=<%= ct.ten%> src=<%= "/assets/cauthus/"+ ct.hinhanh %> width = "300" height = "400" >
						</div>
						<div class="row">
							<div class="col-md-10 col-md-offset-1">
								<div class="table-responsive">          
								  <table class="table">
								    <thead>
								      <tr>
								        <th>Info</th>
								        <th>Data</th>
								      </tr>
								    </thead>
								    <tbody>
								      <tr>
								        <td>Country</td>
								        <td><%= ct.quoctich%></td>
								      </tr>
								      <tr>
								        <td>Date of birth</td>
								        <td><%= ct.ngaysinh%></td>
								      </tr>
								      <tr>
								        <td>Football club</td>
								        <td><%= Doibong.find(ct.doibong_id).ten%></td>
								      </tr>
								      <tr>
								        <td>Height</td>
								        <td><%= ct.chieucao%></td>
								      </tr>
								      <tr>
								        <td>Weight</td>
								        <td><%= ct.cannang%></td>
								      </tr>
								      <tr>
								        <td>Position</td>
								        <td><%= Vitri.find(ct.vitri_id).tenvitri%></td>
								      </tr>
								    </tbody>
								  </table>
								  </div>
							  </div>
						</div>
						     
				   </div>
				    <div class="modal-footer">
				      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				    </div>
				  </div>
				  
				</div>
			</div>  		
	  <%end%>
  <%end%>
</div>

app/views/home/_cauthu_slider.html.erb
<style>
	.carousel-inner>.item> img,
	.carousel-inner>.item>a
	{
		width:313px;
		margin: auto;
	}
</style>

<% if @cauthus != []%>

<div class="row">
	<div>
	  <br>
	  <div id="myCarousel" style="silver" class="carousel slide" data-ride="carousel">
	    <!-- Indicators -->
	    
       <% i=1 -%>

	    <ol style="margin-bottom: 35px" class="carousel-indicators">
	      <% @cauthus.each do |cauthu|-%>
	        <% if cauthu = @cauthus.first -%>
	          <li data-target="#myCarousel" data-slide-to= <%= i%> class="active"></li>
	          <% i+=1 -%>
	        <% else-%>
	          <li data-target="#myCarousel" data-slide-to=<%= i %>></li>
	          <% i+=1 -%>
	        <% end -%>
	      <% end -%>
	    </ol>
	
	    <!-- Wrapper for slides -->
	    <div class="carousel-inner" role="listbox">
	      <div class="item active">
	        <%@cauthu= @cauthus.first%>
	        <center style="font-size: 20px"><b><%= @cauthu.ten%></b></center>
	        <img class="img-thumbnail" alt=<%= @cauthus.first.ten %> src=<%= "/assets/cauthus/"+ @cauthus.first.hinhanh %> >
	        <%= render "home/chitietcauthu_link" %>
		</div>



	
	      <% @cauthus.each do |cauthu|-%>
	      	<%if cauthu != @cauthus.first-%>
	      		<%@cauthu = cauthu%>
	        	<div class="item">
	        		<center style="font-size: 20px"><b><%= cauthu.ten%></b></center>
		          	<img class="img-thumbnail" alt=<%= cauthu.ten.to_s() %> src=<%= "/assets/cauthus/"+cauthu.hinhanh.to_s()%> > 
				  	<%= render "home/chitietcauthu_link" %>
	        	</div>
	      	<% end-%>
	      <% end -%>
	    </div>
	
	    <!-- Left and right controls -->
	    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
	      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
	      <span class="sr-only">Previous</span>
	    </a>
	    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
	      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
	      <span class="sr-only">Next</span>
	    </a>
	  </div>
	</div>
</div>

<% end %>

app/views/home/_chitiet_trandau.html.erb
<!-- Trigger the modal with a button -->
  <!-- Modal -->
<div class="modal fade" id="myModal" role="dialog">
	<div class="modal-dialog">
	
	  <!-- Modal content-->
	  <div class="modal-content">
	    <div class="modal-header">
	      <button type="button" class="close" data-dismiss="modal">&times;</button>
	      <h4 class="modal-title"><center><%= @cauthu.ten%></center></h4>
	    </div>
	    <div class="modal-body">
	    	<div class="row text-center">
				<img alt=<%= @cauthu.ten%> src=<%= "/assets/cauthus/"+ @cauthu.hinhanh %> width = "300" height = "400" >
			</div>
			<div class="row">
				<div class="col-md-10 col-md-offset-1">
					<div class="table-responsive">          
					  <table class="table">
					    <thead>
					      <tr>
					        <th>Thông tin</th>
					        <th>Dữ liệu</th>
					      </tr>
					    </thead>
					    <tbody>
					      <tr>
					        <td>Quốc tịch</td>
					        <td><%= @cauthu.quoctich%></td>
					      </tr>
					      <tr>
					        <td>Ngày sinh</td>
					        <td><%= @cauthu.ngaysinh%></td>
					      </tr>
					      <tr>
					        <td>Đội bóng</td>
					        <td><%= Doibong.find(@cauthu.doibong_id).ten%></td>
					      </tr>
					      <tr>
					        <td>Chiều cao</td>
					        <td><%= @cauthu.chieucao%></td>
					      </tr>
					      <tr>
					        <td>Cân nặng</td>
					        <td><%= @cauthu.cannang%></td>
					      </tr>
					      <tr>
					        <td>Vị trí</td>
					        <td><%= Vitri.find(@cauthu.vitri_id).tenvitri%></td>
					      </tr>
					    </tbody>
					  </table>
					  </div>
				  </div>
			</div>
			     
	   </div>
	    <div class="modal-footer">
	      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	    </div>
	  </div>
	  
	</div>
</div>
  

app/views/home/_chitietcauthu_link.html.erb
<!-- Trigger the modal with a button -->
<center >
  <button style="margin-top:10px;color: black " type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal<%= @cauthu.id%>" >Details...</button>
</center>
  <!-- Modal -->
<div class="modal fade" id="myModal<%= @cauthu.id%>" role="dialog">
	<div class="modal-dialog">
	
	  <!-- Modal content-->
	  <div class="modal-content">
	    <div class="modal-header">
	      <button type="button" class="close" data-dismiss="modal">&times;</button>
	      <h4 class="modal-title"><center><%= @cauthu.ten%></center></h4>
	    </div>
	    <div class="modal-body">
	    	<div class="row text-center">
				<img alt=<%= @cauthu.ten%> src=<%= "/assets/cauthus/"+ @cauthu.hinhanh %> width = "300" height = "400" >
			</div>
			<div class="row">
				<div class="col-md-10 col-md-offset-1">
					<div class="table-responsive">          
					  <table class="table">
					    <thead>
					      <tr>
					        <th>Info</th>
					        <th>Data</th>
					      </tr>
					    </thead>
					    <tbody>
					      <tr>
					        <td>Country</td>
					        <td><%= @cauthu.quoctich%></td>
					      </tr>
					      <tr>
					        <td>Date of Birth</td>
					        <td><%= @cauthu.ngaysinh%></td>
					      </tr>
					      <tr>
					        <td>Club</td>
					        <td><%= Doibong.find(@cauthu.doibong_id).ten%></td>
					      </tr>
					      <tr>
					        <td>Height</td>
					        <td><%= @cauthu.chieucao%></td>
					      </tr>
					      <tr>
					        <td>Weight</td>
					        <td><%= @cauthu.cannang%></td>
					      </tr>
					      <tr>
					        <td>Position</td>
					        <td><%= Vitri.find(@cauthu.vitri_id).tenvitri%></td>
					      </tr>
					    </tbody>
					  </table>
					  </div>
				  </div>
			</div>
			     
	   </div>
	    <div class="modal-footer">
	      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	    </div>
	  </div>
	  
	</div>
</div>
  

app/views/home/_menu_chitietdb.html.erb
<style>
	.well.well-sm div img
	{
		width:995px;
		
	}
.menu_menu ul li a
	{
		color:#000;
		font-size: 26px;
	}
.menu_menu ul li a:hover
	{
		color:#990000;
	}
	.menu_menu ul .active a
	{
		color:#000;
		font-size: 26px;
	}
	.menu_menu ul .active a:hover
	{
		color:#990000;
	}
</style>
<div class="panel panel-info">
	<div class="panel-heading" style="background:url(/assets/content/td3.png) repeat;color: #fff;font-size: 20px;padding:0px 4px 0px 4px">
		<div style="text-align: center">
		<div class="btn-group">
  <button type="button" class="btn btn-danger dropdown-toggle" style="min-width: 230px;background: #990000" data-toggle="dropdown" aria-expanded="false"> 
  	<div style="font-size: 15px;background: #fff;color: #000;width: 210px" >
  	
  		<%= @doibong.ten%> <span class="caret">  </span>
  	</div>
	</button>

  <ul class="dropdown-menu" role="menu">
  	<% Doibong.all.each do |doibong|%>
    <li><a href="<%= "/home/chitietdoibong/"+doibong.id.to_s%>"><%= doibong.ten%></a></li>
    <li class="divider"></li>
    <%end%>	 
  </ul>
</div>
</div>
</div>
</div>

 <div  class="well well-sm" style="width: 100%;background: #990000">
	<% if %>
	<% @huanluyenvien.hinhanh == nil %>
	<strong></strong>
	<% else %>
	 <div><%= link_to image_tag("hlv/" + @huanluyenvien.hinhanh)%></div>
	<%end%>
 </div>
 <div class="menu_menu">
 <ul class="nav nav-tabs nav-justified" style="font-size: 22px;font-weight: 900">
  <li role="presentation" class="active"><%= link_to "News", tinmoi_doibong_path() %></li>
  <li role="presentation"><%= link_to "Data",  dulieu_doibong_path %></li>
  <li role="presentation"><%= link_to "Player", cauthu_doibong_path %></li>
  <li role="presentation"><%= link_to "Match Table", ltd_doibong_path %></li>
  <li role="presentation"><%= link_to "Stadium", sanvandong_doibong_path %></li>
</ul>
</div>

    			

app/views/home/_menu_doibong.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid" style="background-color: ">    
    <div class="navbar-header" >
      <a class="navbar-brand" rel="home" href="#" title="Buy Sell Rent Everyting">
	<div style="margin-top:-11PX;margin-left: -11px"><%= image_tag("logo/BUNDESLIGA.png", :alt => "rss feed" ) %></div>
    </a>     
    </div>
      <div id="thumbs-wrapper">
  <div id="thumbs-container">
  	<%Doibong.all.each do |doibong|%>
  	
  	<a href="<%= "/home/chitietdoibong/"+doibong.id.to_s%>"><img height="52" src="<%= "/assets/logo/"+doibong.logo%>" width="60", class ="logo-doibong"></a>
  	<%end%>	 
  </div>
</div>
</nav>

app/views/home/_trangchu.html.erb
  <script type="text/javascript">
	$(document).ready(function(){
		$("#featured").tabs({fx:{opacity: "toggle"}}).tabs("rotate", 5000, true);
	});
</script>
   <div id="content">
  <div id="left">
  	<div id="content_noibat">
<table width="100%" class="bxh">
<tr>
    	<td class="tuade" colspan="3">
        <a href="#>"><b><p><u> Focus News</u></p></b></a>
        </td>

   </tr>
</table>
</div>
<div id="featured" style="height: 320px">
			  	<% i=1 -%>
		  <ul class="ui-tabs-nav" style="height: 310px">
		  	<%@baiviets.each do |baiviet|%>
	        <li class="ui-tabs-nav-item " style = "overflow: hidden; text-overflow:elipse" id="<%= "nav-fragment-"+ i.to_i.to_s%>">
	        	<a href="<%= "#fragment-"+ i.to_i.to_s%>">
	        				  		        	<% i+=1 -%>
	        		<img style="width: 110px ;height: 54px" src="/assets/tintuc/<%= baiviet["hinhanh"]%>" alt="" />
	        		<span><%= baiviet["tieude"]%></span>
	        	</a>
	        </li>		
	       <%end%>
	      </ul>
	    <!-- First Content -->
	   		<% a=1 -%>
	    <%@baiviets.each do |baiviet|%>
	    <div id="<%= "fragment-"+ a.to_i.to_s%>" class="ui-tabs-panel" style="">
	    	<% a+=1 -%>	
			<img style="width: 410px ;height: 249px" src="/assets/tintuc/<%= baiviet["hinhanh"]%>" alt="" />
			 <div class="info">
				<p style="color: #000">
					<h2 style="margin-top: 65px;white-space: nowrap;text-overflow: ellipsis;overflow: hidden;width: 400px" >
					<a  href="<%= "/home/chitiet_baiviet/"+baiviet["id"].to_s%>" ><%= baiviet["tieude"]%>
				</a>
					</h2>
				</p>
				<p style="color: #000"><%= baiviet["noidung"]%><a class="label label-default" href="<%= "/home/chitiet_baiviet/"+baiviet["id"].to_s%>" >Detail..</a></p>
			 </div>
	    </div>
	    <%end%>
		</div>
	
<div id="content_noibat">
<table width="100%" class="bxh" >
<tr>
    	<td class="tuade" colspan="10">
        <a href="#"><b><p><u><i>Match on today</i></u></p></b></a>
        </td>

</tr>
                	<tr style="color: #fff"  bgcolor="#000" align="center">
                    	<td colspan="4">Match</td>
                        <td colspan="3">Time</td>
                        <td colspan="3">Goals</td>
                        
                    </tr>
                    <tr bgcolor="#E5E5E5">
                    	<td height="24" rowspan="3">1/12</td>
                        <td align="right" style="color:#F00">Bayern München</td>
                        <td style="color:#090">19:30</td>
                        <td>Bvb Dormun</a></td>
                        <td align="center"><strong>1/4 : 0</strong></td>
                                                					
                        <td>0.89</td>
                        <td>-0.95</td>
                        <td><strong>2 3/4</strong></td>
                        <td>0.96</td>
                        <td>0.94</td>
                        
                    </tr>
                    <tr bgcolor="#D4D4D4">
                    	<td align="right" style="color:#F00">Wolfsburg</td>
                        <td style="color:#090">19:30</td>
                        <td>Leverkusen</a></td>
                        <td align="center"><strong>1/2 : 0</strong></td>
                                                					
                        <td>-0.91</td>
                        <td>0.85</td>
                        <td><strong>2 1/4</strong></td>
                        <td>0.86</td>
                        <td>-0.96</td>
                    </tr>
  </table>
  </div>
  
<div id="content_noibat">
<table width="100%" class="table_about" align="center" cellpadding="5">
	<tr>
    	<td colspan="2" class="tuade"style=" background:url(/assets/content/td.png)" >
         <a href="#"><p><b>DFL News</b></p></a>
        </td>	

    </tr>
    	<tr>
        <td><img width="254" height="145" src="/assets/content/img_about1.PNG" frameborder="0" allowfullscreen></td>
    	<td>
			<a href=""><h2><b>Technology confirmed</b></h2></a> Bundesliga will use goal-line technology at its 18 stadiums from scratch 2015/16 season after a largely elected from more than 18 clubs
				
			<br />
        </td>

    </tr>
        	<tr>
            <td><img  width="254" height="145" src="/assets/content/img_about2.PNG" frameborder="0" allowfullscreen></td>
    	<td>
		<a href="about2.php"><h2><b>2015/16 schedule set</b></h2></a> The full schedule for the season 2015/16 interim and Bundesliga 2 Bundesliga campaign has been completed, with more days DFB Cup<br />
        </td>

    </tr>
        	<tr>
            <td><img width="254" height="145" src="/assets/content/img_about3.PNG" frameborder="0" allowfullscreen></td>
    	<td>
			<a href="about3.php"><h2><b>Right handed</b></h2></a> Audiovisual media rights for Bundesliga football has been given a further 18 countries, a move that will double the income from copyright rather 2015/16<br />
        </td>

    </tr>
    </table>

</div>

<div id="content_noibat">
<table width="100%" class="table_vd" align="center">
	<tr>
    	<td class="tuade" colspan="4">
        <a href="#"><b><p><u>Goals videos</u></p></b></a>
        </td>
   </tr>
</table>
 <div id="products" class="list-group">
	 <%@videos.each do |video|%>
        <div class="item  col-xs-4 col-lg-4">
            <div class="thumbnail" style = "height: 300px">
                <video class="group list-group-image" src="/assets/videos/<%= video["video"]%> "  controls="controls"></video>
                <div class="caption">
                    <h5 class="group inner list-group-item-heading text-center">
                      <b><%= video["tieude"]%> </b></h5>
                    <p class="group inner list-group-item-text text-justify" style = "height: 100px">
                        <%= video["tuade"]%></p>
                    <div class="row">
                        <div class="col-xs-12 col-md-6">
                            <a class="btn btn-success" href="<%= "/home/chitiet_video/"+video["id"].to_s%>"> Details..</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
      <%end%>
    </div>
</div>
  	</div>
 <div id="right">
<%=render "home/right" %>
 	</div>
                       </div>
                       <div style="clear:both"></div>

app/views/home/index.html.erb
<%=render "home/trangchu" %>

app/views/home/players.html.erb
<div id="content">
	<div id="content_content">		 
	<div class="panel panel-info">
	<%=render "home/menu_chitietdoibong" %>	
	
	<div class="col-md-3">
		<%= render "home/list_cauthu_doibong"%>
	</div>
	
	<div class="col-md-6">
		<%= render "home/cauthu_slider"%>
	</div>

	<div class="col-md-3">
		<%= render "home/timkiem_cauthu"%>
	</div>
	</div>
	<div style="clear:both"></div>
</div>
</div>