config/routes.rb
Rails.application.routes.draw do  
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
  resources :videos
  resources :baiviets
    
  resources :banthangs

  resources :phamlois

  resources :thephats

  resources :chitiettrandaus

  resources :trandaus

  resources :lichthidaus

  resources :chitietbxhs

  resources :bangxephangs

  resources :vongdaus

  resources :sanvandongs

  resources :cauthus

  resources :loaimedia

  resources :lenxuonghangs

  resources :doibongs

  resources :vitris

  resources :huanluyenviens

  resources :baiviets

  get 'home/index'
  get '/admin/index', to: 'admin#index', as: 'admin_index'
  
  get 'home/index',to: 'home#index', as: 'index'
  get '/home/news', to: 'home#news', as: 'news'
  get '/home/watch', to: 'home#watch', as: 'watch'
  get '/home/players', to: 'home#players', as: 'players'
  get '/home/stats', to: 'home#stats', as: 'stats'
  get '/home/about', to: 'home#about', as: 'about'
  get '/home/fanzone', to: 'home#fanzone', as: 'fanzone'
  get '/home/chitietdoibong/:id', to: 'home#chitietdoibong', as: 'chitietdoibong'
  get '/home/chitietdoibong/:id', to: 'home#tinmoi_doibong', as: 'tinmoi_doibong'
  get '/home/dulieu_doibong/:id', to: 'home#dulieu_doibong', as: 'dulieu_doibong'
  get '/home/cauthu_doibong/:id', to: 'home#cauthu_doibong', as: 'cauthu_doibong'
  get '/home/ltd_doibong/:id', to: 'home#ltd_doibong', as: 'ltd_doibong'
  get '/home/sanvandong_doibong/:id', to: 'home#sanvandong_doibong', as: 'sanvandong_doibong'
  get '/home/chitiet_baiviet/:id', to: 'home#chitiet_baiviet', as: 'chitiet_baiviet'
  get '/home/chitiet_video/:id', to: 'home#chitiet_video', as: 'chitiet_video'
  
  root to: "home#index"
  post '/change_locale/:locale', to: 'setting#change_locale', as: :change_locale
  post '/change_stat/:stt', to: 'home#change_stat', as: :change_stat
  post '/find_cauthu_ten', to: 'home#find_cauthu_ten', as: :find_cauthu_ten
  
  
  post '/admin_xuly', to: 'admin#xuly', as: :admin_xuly
  

end

app/models/baiviet.rb
class Baiviet < ActiveRecord::Base
end

app/models/bangxephang.rb
class Bangxephang < ActiveRecord::Base
  belongs_to :vongdau
end

app/models/banthang.rb
class Banthang < ActiveRecord::Base
  belongs_to :cauthu
  belongs_to :chitiettrandau
end

app/models/cauthu.rb
class Cauthu < ActiveRecord::Base
  belongs_to :vitri
  belongs_to :doibong
end

app/models/chitietbxh.rb
class Chitietbxh < ActiveRecord::Base
  belongs_to :bangxephang
  belongs_to :doibong
  belongs_to :lenxuonghang
end

app/models/doibong.rb
class Doibong < ActiveRecord::Base
  belongs_to :huanluyenvien
end

app/models/huanluyenvien.rb
class Huanluyenvien < ActiveRecord::Base
end

app/models/lenxuonghang.rb
class Lenxuonghang < ActiveRecord::Base
end

app/models/lichthidau.rb
class Lichthidau < ActiveRecord::Base
  belongs_to :vongdau
end

app/models/loaimedium.rb
class Loaimedium < ActiveRecord::Base
end

app/models/phamloi.rb
class Phamloi < ActiveRecord::Base
  belongs_to :thephat
  belongs_to :cauthu
  belongs_to :chitiettrandau
end

app/models/sanvandong.rb
class Sanvandong < ActiveRecord::Base
  belongs_to :doibong
end

app/models/thephat.rb
class Thephat < ActiveRecord::Base
end

app/models/trandau.rb
class Trandau < ActiveRecord::Base
  has_one :doinha, :class_name => "doibong"
  has_one :doikhach, :class_name => "doibong"
  belongs_to :vongdau
  belongs_to :sanvandong
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/videos.rb
class Videos < ActiveRecord::Base
end

app/models/vitri.rb
class Vitri < ActiveRecord::Base
end

app/models/vongdau.rb
class Vongdau < ActiveRecord::Base
end

app/controllers/huanluyenviens_controller.rb
class HuanluyenviensController < ApplicationController
  before_action :set_huanluyenvien, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @huanluyenviens = Huanluyenvien.all
    respond_with(@huanluyenviens)
  end

  def show
    respond_with(@huanluyenvien)
  end

  def new
    @huanluyenvien = Huanluyenvien.new
    respond_with(@huanluyenvien)
  end

  def edit
  end

  def create
    @huanluyenvien = Huanluyenvien.new(huanluyenvien_params)
    @huanluyenvien.save
    respond_with(@huanluyenvien)
  end

  def update
    @huanluyenvien.update(huanluyenvien_params)
    respond_with(@huanluyenvien)
  end

  def destroy
    @huanluyenvien.destroy
    respond_with(@huanluyenvien)
  end

  private
    def set_huanluyenvien
      @huanluyenvien = Huanluyenvien.find(params[:id])
    end

    def huanluyenvien_params
      params.require(:huanluyenvien).permit(:ten, :tuoi, :quoctich)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/huanluyenviens_helper.rb
module HuanluyenviensHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/huanluyenviens/_form.html.erb
<div class="row">
	<div class="col-md-4 col-md-offset-4">

		<%= form_for(@huanluyenvien) do |f| %>
		  <% if @huanluyenvien.errors.any? %>
		    <div id="error_explanation">
		      <h2><%= pluralize(@huanluyenvien.errors.count, "error") %> prohibited this huanluyenvien from being saved:</h2>
		
		      <ul>
		      <% @huanluyenvien.errors.full_messages.each do |message| %>
		        <li><%= message %></li>
		      <% end %>
		      </ul>
		    </div>
		  <% end %>
		
		  <div class="field">
		    <%= f.label :ten,"Name"%><br>
		    <%= f.text_field :ten, :class =>"form-control" %>
		  </div>
		  <div class="field">
		    <%= f.label :tuoi, "Age" %><br>
		    <%= f.text_field :tuoi , :class =>"form-control" %>
		  </div>
		  <div class="field">
		    <%= f.label :quoctich,"Country" %><br>
		    <%= f.text_field :quoctich , :class =>"form-control" %>
		  </div>
		  <div class="field">

	      <%= f.label :hinhanh, "Image"%><br />
	      <div class="input-group">
				  <span class="input-group-addon btn btn-info btn-file" id="basic-addon1">Browser...<input type="file"></span>
				  <input type="text" class="form-control" placeholder="File name" aria-describedby="basic-addon1" id= "huanluyenvien_hinhanh" name = "huanluyenvien[hinhanh]" value= <%= @huanluyenvien.hinhanh%> >
				</div>
	    </div>
		  <div class="actions">
		    <%= f.submit "Submit", :class=>"btn btn-success"%>
		  </div>
		<% end %>
	</div>
</div>

app/views/huanluyenviens/_index.html.erb
<h1 class="text-center">Listing Assistants</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Country</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @huanluyenviens.each do |huanluyenvien| %>
      <tr>
        <td><%= huanluyenvien.ten %></td>
        <td><%= huanluyenvien.tuoi %></td>
        <td><%= huanluyenvien.quoctich %></td>
        <% if huanluyenvien.hinhanh != nil %>
          <td><%= image_tag("hlv/"+huanluyenvien.hinhanh, :class => "round-image-50") %></td>
        <% else %>
          <td> nil </td>
        <% end %>
        <td><%= link_to 'Show', huanluyenvien %></td>
        <td><%= link_to 'Edit', edit_huanluyenvien_path(huanluyenvien) %></td>
        <td><%= link_to 'Destroy', huanluyenvien, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Assistant', new_huanluyenvien_path %>

app/views/huanluyenviens/edit.html.erb
<h1 class="text-center">Editing Assistant</h1>

<%= render 'form' %>

<%= link_to 'Show', @huanluyenvien %> |
<%= link_to 'Back', admin_index_path %>

app/views/huanluyenviens/new.html.erb
<h1 class="text-center">New Assistant</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_index_path %>

app/views/huanluyenviens/show.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<p id="notice"><%= notice %></p>
		
		<p>
		  <strong>Name:</strong>
		  <%= @huanluyenvien.ten %>
		</p>
		
		<p>
		  <strong>Age:</strong>
		  <%= @huanluyenvien.tuoi %>
		</p>
		
		<p>
		  <strong>Country:</strong>
		  <%= @huanluyenvien.quoctich %>
		</p>
		
		<p>
		  <strong>Image:</strong>
		  <%= @huanluyenvien.hinhanh %>
		</p>
		
		<%= link_to 'Edit', edit_huanluyenvien_path(@huanluyenvien) %> |
		<%= link_to 'Back', admin_index_path %>
	</div>
</div>