config/routes.rb
Rails.application.routes.draw do  
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
  resources :videos
  resources :baiviets
    
  resources :banthangs

  resources :phamlois

  resources :thephats

  resources :chitiettrandaus

  resources :trandaus

  resources :lichthidaus

  resources :chitietbxhs

  resources :bangxephangs

  resources :vongdaus

  resources :sanvandongs

  resources :cauthus

  resources :loaimedia

  resources :lenxuonghangs

  resources :doibongs

  resources :vitris

  resources :huanluyenviens

  resources :baiviets

  get 'home/index'
  get '/admin/index', to: 'admin#index', as: 'admin_index'
  
  get 'home/index',to: 'home#index', as: 'index'
  get '/home/news', to: 'home#news', as: 'news'
  get '/home/watch', to: 'home#watch', as: 'watch'
  get '/home/players', to: 'home#players', as: 'players'
  get '/home/stats', to: 'home#stats', as: 'stats'
  get '/home/about', to: 'home#about', as: 'about'
  get '/home/fanzone', to: 'home#fanzone', as: 'fanzone'
  get '/home/chitietdoibong/:id', to: 'home#chitietdoibong', as: 'chitietdoibong'
  get '/home/chitietdoibong/:id', to: 'home#tinmoi_doibong', as: 'tinmoi_doibong'
  get '/home/dulieu_doibong/:id', to: 'home#dulieu_doibong', as: 'dulieu_doibong'
  get '/home/cauthu_doibong/:id', to: 'home#cauthu_doibong', as: 'cauthu_doibong'
  get '/home/ltd_doibong/:id', to: 'home#ltd_doibong', as: 'ltd_doibong'
  get '/home/sanvandong_doibong/:id', to: 'home#sanvandong_doibong', as: 'sanvandong_doibong'
  get '/home/chitiet_baiviet/:id', to: 'home#chitiet_baiviet', as: 'chitiet_baiviet'
  get '/home/chitiet_video/:id', to: 'home#chitiet_video', as: 'chitiet_video'
  
  root to: "home#index"
  post '/change_locale/:locale', to: 'setting#change_locale', as: :change_locale
  post '/change_stat/:stt', to: 'home#change_stat', as: :change_stat
  post '/find_cauthu_ten', to: 'home#find_cauthu_ten', as: :find_cauthu_ten
  
  
  post '/admin_xuly', to: 'admin#xuly', as: :admin_xuly
  

end

app/models/baiviet.rb
class Baiviet < ActiveRecord::Base
end

app/models/bangxephang.rb
class Bangxephang < ActiveRecord::Base
  belongs_to :vongdau
end

app/models/banthang.rb
class Banthang < ActiveRecord::Base
  belongs_to :cauthu
  belongs_to :chitiettrandau
end

app/models/cauthu.rb
class Cauthu < ActiveRecord::Base
  belongs_to :vitri
  belongs_to :doibong
end

app/models/chitietbxh.rb
class Chitietbxh < ActiveRecord::Base
  belongs_to :bangxephang
  belongs_to :doibong
  belongs_to :lenxuonghang
end

app/models/doibong.rb
class Doibong < ActiveRecord::Base
  belongs_to :huanluyenvien
end

app/models/huanluyenvien.rb
class Huanluyenvien < ActiveRecord::Base
end

app/models/lenxuonghang.rb
class Lenxuonghang < ActiveRecord::Base
end

app/models/lichthidau.rb
class Lichthidau < ActiveRecord::Base
  belongs_to :vongdau
end

app/models/loaimedium.rb
class Loaimedium < ActiveRecord::Base
end

app/models/phamloi.rb
class Phamloi < ActiveRecord::Base
  belongs_to :thephat
  belongs_to :cauthu
  belongs_to :chitiettrandau
end

app/models/sanvandong.rb
class Sanvandong < ActiveRecord::Base
  belongs_to :doibong
end

app/models/thephat.rb
class Thephat < ActiveRecord::Base
end

app/models/trandau.rb
class Trandau < ActiveRecord::Base
  has_one :doinha, :class_name => "doibong"
  has_one :doikhach, :class_name => "doibong"
  belongs_to :vongdau
  belongs_to :sanvandong
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/videos.rb
class Videos < ActiveRecord::Base
end

app/models/vitri.rb
class Vitri < ActiveRecord::Base
end

app/models/vongdau.rb
class Vongdau < ActiveRecord::Base
end

app/controllers/trandaus_controller.rb
class TrandausController < ApplicationController
  before_action :set_trandau, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @trandaus = Trandau.all
    respond_with(@trandaus)
  end

  def show
    respond_with(@trandau)
  end

  def new
    @trandau = Trandau.new
    respond_with(@trandau)
  end

  def edit
  end

  def create
    @trandau = Trandau.new(trandau_params)
    @trandau.save
    respond_with(@trandau)
  end

  def update
    @trandau.update(trandau_params)
    respond_with(@trandau)
  end

  def destroy
    @trandau.destroy
    respond_with(@trandau)
  end

  private
    def set_trandau
      @trandau = Trandau.find(params[:id])
    end

    def trandau_params
      params.require(:trandau).permit(:banthangdoinha, :banthangdoikhach, :doinha_id, :doikhach_id, :thoigian, :vongdau_id, :sanvandong_id)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/trandaus_helper.rb
module TrandausHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/trandaus/_form.html.erb
<div class="row">
	<div class="col-md-4 col-md-offset-4">

		<%= form_for(@trandau) do |f| %>
		  <% if @trandau.errors.any? %>
		    <div id="error_explanation">
		      <h2><%= pluralize(@trandau.errors.count, "error") %> prohibited this trandau from being saved:</h2>
		
		      <ul>
		      <% @trandau.errors.full_messages.each do |message| %>
		        <li><%= message %></li>
		      <% end %>
		      </ul>
		    </div>
		  <% end %>
		
		  <div class="field">
		    <%= f.label :banthangdoinha , "Goal of home club"%><br>
		    <%= f.text_field :banthangdoinha , :class=>"form-control"%>
		  </div>
		  <div class="field">
		    <%= f.label :banthangdoikhach,"Goal of visiter" %><br>
		    <%= f.text_field :banthangdoikhach , :class=>"form-control" %>
		  </div>
			<div class="form-group">
		    <%= f.label :doinha_id, "Home" %><br>    
			    <%= f.select(:doinha_id,[],{},{:class =>"form-control"} ) do %>
			  		<% Doibong.all.each do |c| -%>
			    	<%= content_tag(:option, c.ten, value: c.id) %>
			  	<% end %>
				<% end %>
		  </div>
		  <div class="form-group">
		    <%= f.label :doikhach_id, "Visiter" %><br>    
			    <%= f.select(:doikhach_id,[],{},{:class =>"form-control"} ) do %>
			  		<% Doibong.all.each do |c| -%>
			    	<%= content_tag(:option, c.ten, value: c.id) %>
			  	<% end %>
				<% end %>
		  </div>  
		  <div class="field">
		    <%= f.label :thoigian, "Time" %><br>
		    <%= f.datetime_select :thoigian , :class=>"form-control"%>
		  </div>
		  
		  <div class="form-group">
		    <%= f.label :vongdau_id, "Number of Round" %><br>    
			    <%= f.select(:vongdau_id,[],{},{:class =>"form-control"} ) do %>
			  		<% Vongdau.all.each do |c| -%>
			    	<%= content_tag(:option, c.stt, value: c.id) %>
			  	<% end %>
				<% end %>
		  </div>
		  <div class="actions">
		    <%= f.submit "Submig", :class=>"btn btn-success"%>
		  </div>
		<% end %>
	</div>
	</div>

app/views/trandaus/_index.html.erb
<h1 class="text-center">Listing matches</h1>

<table class="table">
  <thead>
    <tr>
      <th>Goal of home club:</th>
      <th>Goal of visiter:</th>
      <th>Home club:</th>
      <th>Visiter:</th>
      <th>Time:</th>
      <th>Number of round:</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trandaus.each do |trandau| %>
      <tr>
        <td><%= trandau.banthangdoinha %></td>
        <td><%= trandau.banthangdoikhach %></td>
        <td><%= Doibong.where(:id => trandau.doinha_id).first.ten %></td>
        <td><%= Doibong.where(:id => trandau.doikhach_id).first.ten %></td>
        <td><%= trandau.thoigian %></td>
        <td><%= Vongdau.where(:id => trandau.vongdau).first.stt %></td>      
        <td><%= link_to 'Show', trandau %></td>
        <td><%= link_to 'Edit', edit_trandau_path(trandau) %></td>
        <td><%= link_to 'Destroy', trandau, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Match', new_trandau_path %>

app/views/trandaus/edit.html.erb
<h1 class="text-center">Editing Match</h1>

<%= render 'form' %>

<%= link_to 'Show', @trandau %> |
<%= link_to 'Back', admin_index_path %>

app/views/trandaus/new.html.erb
<h1 class="center">New Match</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_index_path %>

app/views/trandaus/show.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">

		<p id="notice"><%= notice %></p>
		
		<p>
		  <strong>Goal of home club:</strong>
		  <%= @trandau.banthangdoinha %>
		</p>
		
		<p>
		  <strong>Goal of visiter:</strong>
		  <%= @trandau.banthangdoikhach %>
		</p>
		
		<p>
		  <strong>Home club:</strong>
		  <%= Doibong.where( :id => @trandau.doinha_id).first.ten %>
		</p>
		
		<p>
		  <strong>Visiter:</strong>
		  <%= Doibong.where( :id => @trandau.doikhach_id).first.ten %>
		</p>
		
		<p>
		  <strong>Time:</strong>
		  <%= @trandau.thoigian %>
		</p>
		
		<p>
		  <strong>Number of round:</strong>
		  <%= Vongdau.where(:id => @trandau.vongdau).first.stt %>
		</p>
		
		
		<%= link_to 'Edit', edit_trandau_path(@trandau) %> |
		<%= link_to 'Back', admin_index_path %>
	</div>
</div>